### ISSUE TITLE
Status of this action?

### ISSUE THREAD

**Issue by famod** [eddumelendez/sdkman-action#7]
First off: thanks for providing such an action!

Right now I can only see two "preview" releases. What's missing to get this action out of preview state?

Related to this: Does this action use GitHub caching functionality? I'm not very familiar with it myself, but I have seen multiple actions using caching in the background.

**Comment by eddumelendez** [comment]
> What's missing to get this action out of preview state?

This action can be used as you can see in the example below. However, it has not been published in the marketplaces but it is not a blocker.

> Does this action use GitHub caching functionality?

Take a look at [this example](https://github.com/awspring/spring-cloud-aws/blob/2.3.x/.github/workflows/release.yml)
